
===========================
SnmpBooster Troubleshooting
===========================

Check your config
=================

  - Have you defined the poller module name?
  - Have you defined the correct path to the directory containing your Defaults*.ini files?
  - Have you addded the Snmpbooster module to your arbiter, poller, scheduler?
  - Have you added copied the genDevConfig templates.cfg in shinken/packs/network/SnmpBooster/
  - Have you installed PySNMP, mongodb and other dependencies?

Software version consistency
============================

Shinken and SnmpBooster now require **the same Python and Pyro version on all hosts running a Shinken daemon**.

If you cannot use the packaged version of Python and its modules (Pyro, mongodb, etc.). Use `virtualenv`_ to declare a python version to use and install all required modules in that virtualenv.

.. _virtualenv: http://pypi.python.org/pypi/virtualenv

Software version requirements
=============================

Have you verified that the :ref:`requirements <setup_snmp_booster_module>` are met. Python, PySNMP, Shinken, Pyro, mongodb, etc.

Validate your check command arguments
=====================================

Use the check_plugin command and comment out the module to learn what were the exact arguments sent by the poller.
This will permit you to validate all the arguments, like snmp community string, inheritance, template application, etc.

Validate connectivity
=====================

Take a packet trace using a tool like Wireshark to validate that the remote host is responding.
    * Has the host responded
    * Is SnmpBooster repeating the request more often than the polling interval. 
        * If you are seeing repeated requests your device may have a compatibility issues. 
        * Save an snmpwalk of the device, get a packet trace using Wireshark, set the poller to debug and save the poller.log file (``/var/log/shinken/pollerd.log``). Send all three to the SnmpBooster developers.

.. note::

    It is normal to see one or more bulkGet requests if you are getting large amounts of data. Ex. a 24 port switch will take 2-3 request packets.

Performance
===========

Make sure you have a low latency connection to your mongodb from the Poller. 
Check that mongodb is running: ``netstat -a | grep mongodb``

Faulty Template
===============

A bad snmp_template file was distributed in the genDevConfig sample-config directory, there were two glaring errors.

This was fixed on 2012-10-16. Make sure you update your template, or use the data from the wiki.

Note that the template should be called: SnmpBooster-template.cfg to make it easier to troubleshoot in the logs. So when you search for SnmpBooster in your logs it will show up as well.

Log files
=========

All warnings and errors generated by the SnmpBooster module start with "[SnmpBooster] error text" and are logged using the standard Shinken logger.

The Arbiter daemon can output initial configuration, loading of host,service keys in mongodb type error messages.
The Scheduler daemon can output scheduling and alert related messages.
The Poller daemon can output messages related to instance mapping, acquisition timeouts, invalid community strings, cache failures and more. These are available in the Web interface, as they are placed in the check results for the service.

You can simply do a ``grep SnmpBooster *`` in your shinken/var directory to see the latest messages related to the SnmpBooster module. You can also sort messages by timestamp to make it easy to find where and when errors occurred.

::

    cd shinken/var
    grep SnmpBooster *


Error codes
===========

code 0101
    =========== ===========================================================================
    Type        INFO
    Description SNMP Booster module starts loading
    File        `__init__.py`
    =========== ===========================================================================

code 0102
    =========== ===========================================================================
    Type        ERROR
    Description The attribute **loaded_by** is not set in the Shinken configuration
    File        `__init__.py`
    =========== ===========================================================================

code 0103
    =========== ===========================================================================
    Type        ERROR
    Description The attribute **loaded_by** must be `poller`, `scheduler` or `arbiter` and
                this is not the case
    File        `__init__.py`
    =========== ===========================================================================

code 0201
    =========== ===========================================================================
    Type        ERROR
    Description **PySNMP** module can not be loaded. Please checks your installation
    File        `libs/checks.py`
    =========== ===========================================================================

code 0202
    =========== ===========================================================================
    Type        ERROR
    Description The current service is not found in the cache (MongoDB). Maybe you flush it
                ? Check your Shinken configuration and try to restart the Arbiter to 
                refill the cache (MongoDB)
    File        `libs/checks.py`
    =========== ===========================================================================

code 0501
    =========== ===========================================================================
    Type        WARNING
    Description The Poller didn't found the asked service in the cache (MongoDB). This
                error should not appear. Please open an issue on GitHub, if you get it.
    File        `libs/results.py`
    =========== ===========================================================================

code 0502
    =========== ===========================================================================
    Type        WARNING
    Description We try to get data from a service which the mapping is not done. We have
                four possible reasons:

                * The host is down
                * The mapping name set in the Shinken service configuration has an error.
                  Please check your configuration
                * The mapping is not finished yet it will be done in few moments
                * The instance name set in the Shinken service configuration has an error
                  and it will never found in the mapping SNMP table. Please check your
                  configuration
    File        `libs/results.py`
    =========== ===========================================================================

code 0601
    =========== ===========================================================================
    Type        ERROR
    Description **PySNMP** module can not be loaded. Please checks your installation
    File        `libs/snmpworker.py`
    =========== ===========================================================================

code 0602
    =========== ===========================================================================
    Type        INFO
    Description The SNMP worker thread is starting
    File        `libs/snmpworker.py`
    =========== ===========================================================================

code 0603
    =========== ===========================================================================
    Type        ERROR
    Description We got a SNMP request which is not `get`, `getnext` or `getbulk`
                Please open an issue on GitHub, if you get it.
    File        `libs/snmpworker.py`
    =========== ===========================================================================

code 0604
    =========== ===========================================================================
    Type        INFO
    Description The SNMP worker thread is now stopped
    File        `libs/snmpworker.py`
    =========== ===========================================================================

code 0605
    =========== ===========================================================================
    Type        INFO
    Description The SNMP worker thread will be stopped
    File        `libs/snmpworker.py`
    =========== ===========================================================================

code 0606
    =========== ===========================================================================
    Type        ERROR
    Description We got a SNMP error. This could be a timeout, a bad response, ...
    File        `libs/snmpworker.py`
    =========== ===========================================================================

code 0701
    =========== ===========================================================================
    Type        ERROR
    Description We got a trigger error. It seems that the datasource name use in the
                trigger doesn't exist. Please check your triggers definitions
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0702
    =========== ===========================================================================
    Type        ERROR
    Description We didn't found any collected data in the cache (MongoDB) to use in the
                trigger. We have four possible reasons:

                * The SNMP request is not finished. We have to wait the next check
                * The oid asked doesn't exists and we never get a value. Please check your
                  Shinken service configuration
                * The host is down
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0703
    =========== ===========================================================================
    Type        ERROR
    Description We didn't found any computed data in the cache (MongoDB) to use in the
                trigger. We have two possible reasons:

                * The current service use a datasource which is a DERIVE, so we need TWO
                  values to compute the derive.
                * We got an error during the value computation
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0704
    =========== ===========================================================================
    Type        ERROR
    Description We got an error during the execution of trigger function.
                The argument passed to the trigger function has a wrong type or 
                is empty. Please check your trigger configuration
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0705
    =========== ===========================================================================
    Type        ERROR
    Description We got an error during the execution of trigger function. The trigger
                function doesn't exist. Please check your trigger
                configuration or if it's a new function open an issue on GitHub
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0706
    =========== ===========================================================================
    Type        ERROR
    Description We didn't found the asked datasource name defined in the trigger. This
                could be a typo. Please check your trigger configuration
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0707
    =========== ===========================================================================
    Type        ERROR
    Description We got an error during the execution of a trigger. Please check your
                trigger configuration
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0708
    =========== ===========================================================================
    Type        INFO
    Description The trigger triggered. It means the service state will be WARNING or
                CRITICAL
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0709
    =========== ===========================================================================
    Type        ERROR
    Description Unknown trigger error. Maybe it's a good idea to report a bug ?
    File        `libs/trigger.py`
    =========== ===========================================================================

code 0801
    =========== ===========================================================================
    Type        WARNING
    Description The parameter **-M** or **--max_rep_map** define in the check command has a
                bad format. Please check your Shinken configuration
    File        `libs/utils.py`
    =========== ===========================================================================

code 0802
    =========== ===========================================================================
    Type        WARNING
    Description The parameter **-g** or **--request_group_size** define in the check
                command has a bad format. Please check your Shinken configuration
    File        `libs/utils.py`
    =========== ===========================================================================

code 0901
    =========== ===========================================================================
    Type        ERROR
    Description **configobj** module can not be loaded. Please checks your installation
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 0902
    =========== ===========================================================================
    Type        INFO
    Description The SNMP Booster module is reading datasource file
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 0903
    =========== ===========================================================================
    Type        INFO
    Description The SNMP Booster module is reading datasource files
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 0904
    =========== ===========================================================================
    Type        ERROR
    Description We got an error merging datasource files. Please check your configuration
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 0905
    =========== ===========================================================================
    Type        ERROR
    Description We got an error merging datasource files. Please check your configuration
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 0906
    =========== ===========================================================================
    Type        ERROR
    Description We got an error during the conversion of the datasource configuration from
                ini format to python dictionnary format. Please check your configuration
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 0907
    =========== ===========================================================================
    Type        ERROR
    Description We got an error during the serialization of service configuration just
                before put it in the cache (MongoDB)
    File        `snmpbooster_arbiter.py`
    =========== ===========================================================================

code 1001
code 1002
code 1003
code 1004
code 1005
code 1006
code 1007
code 1101
code 1102
code 1103
code 1201
code 1202
code 1203
code 1204
code 1205
code 1206
code 1207

Errors should be fairly explicit and mean what they say, though there can be exceptions. Lets try to clear some of them.

Arbiter log errors
~~~~~~~~~~~~~~~~~~

``Missing ds_oid``

    This means that a variable in your OID definitions is missing, or your DATASOURCE is not named correctly or your ds_oid variable is missing. There is a typo in your ds_oid variable (ex. ds-oid, or ds_oid = $OidNameIncorrectFFFRA.%(instance)s).

``Datasource not defined``

    Your DSTEMPLATE uses a DATASOURCE that doesn't exist check the [DataSourceName] you are referring to. Does it contain the expected OID variable, $OidName.

``Missing ds_type``

    The DATASOURCE always needs to have a ds_type definition, GAUGE, COUNTER, DERIVE, TEXT, TIMETICK, DERIVE64, COUNTER64.

Poller log errors
~~~~~~~~~~~~~~~~~

Problems with calculations, repeated polling, hosts not responding, etc.


